/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedPathsRouteImport } from './routes/_authenticated/paths'
import { Route as AuthenticatedInstructorsRouteImport } from './routes/_authenticated/instructors'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/_authenticated/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/_authenticated/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPathsRoute = AuthenticatedPathsRouteImport.update({
  id: '/_authenticated/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInstructorsRoute =
  AuthenticatedInstructorsRouteImport.update({
    id: '/_authenticated/instructors',
    path: '/instructors',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/_authenticated/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/instructors': typeof AuthenticatedInstructorsRoute
  '/paths': typeof AuthenticatedPathsRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/instructors': typeof AuthenticatedInstructorsRoute
  '/paths': typeof AuthenticatedPathsRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/instructors': typeof AuthenticatedInstructorsRoute
  '/_authenticated/paths': typeof AuthenticatedPathsRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/courses'
    | '/instructors'
    | '/paths'
    | '/practice'
    | '/pricing'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/courses'
    | '/instructors'
    | '/paths'
    | '/practice'
    | '/pricing'
    | '/'
  id:
    | '__root__'
    | '/login'
    | '/_authenticated/courses'
    | '/_authenticated/instructors'
    | '/_authenticated/paths'
    | '/_authenticated/practice'
    | '/_authenticated/pricing'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedInstructorsRoute: typeof AuthenticatedInstructorsRoute
  AuthenticatedPathsRoute: typeof AuthenticatedPathsRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/paths': {
      id: '/_authenticated/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof AuthenticatedPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/instructors': {
      id: '/_authenticated/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof AuthenticatedInstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedInstructorsRoute: AuthenticatedInstructorsRoute,
  AuthenticatedPathsRoute: AuthenticatedPathsRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
